import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { auditDiscussionSidebar } from "../src/collaborative-discussion-sidebar-audit.js";

const packet = JSON.parse(readFileSync(new URL("../sample/discussion-sidebar-packet.json", import.meta.url), "utf8"));
const result = auditDiscussionSidebar(packet);

mkdirSync(new URL("../docs/", import.meta.url), { recursive: true });
writeFileSync(new URL("../docs/discussion-sidebar-audit-report.json", import.meta.url), `${JSON.stringify(result, null, 2)}\n`);
writeFileSync(new URL("../docs/demo.svg", import.meta.url), renderSvg(result));

console.log(`Discussion sidebar audit: ${result.ready ? "ready" : "not ready"}`);
console.log(`Project: ${result.project.title}`);
console.log(`Threads: ${result.counts.threads}`);
console.log(`Blockers: ${result.counts.blockers}`);
console.log(`Warnings: ${result.counts.warnings}`);
console.log(`Reviewer tasks: ${result.counts.reviewerTasks}`);
console.log(`Audit digest: ${result.exportPacket.auditDigest}`);

function renderSvg(result) {
  const blockers = result.findings.filter((finding) => finding.severity === "blocker");
  const warnings = result.findings.filter((finding) => finding.severity === "warning");
  const tasks = result.reviewerTasks;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720" role="img" aria-labelledby="title desc">
  <title id="title">Collaborative discussion sidebar audit demo</title>
  <desc id="desc">A storyboard showing section-scoped discussion coverage, blockers, warnings, and export packet digest.</desc>
  <rect width="1280" height="720" fill="#f7f4ee"/>
  <rect x="56" y="48" width="1168" height="624" rx="16" fill="#ffffff" stroke="#24211d" stroke-width="2"/>
  <text x="96" y="108" font-family="Inter, Arial, sans-serif" font-size="34" font-weight="700" fill="#24211d">Discussion Sidebar Audit</text>
  <text x="96" y="146" font-family="Inter, Arial, sans-serif" font-size="18" fill="#5d5750">Section-scoped threads, pinned evidence, decisions, and reviewer handoff packet</text>
  ${card(96, 194, "Coverage", `${result.sidebarCoverage.scopedSections}/${result.sidebarCoverage.totalSections} sections`, "Sidebar threads are attached to manuscript sections or files.")}
  ${card(368, 194, "Blockers", String(result.counts.blockers), blockers.slice(0, 2).map((finding) => finding.code).join(" / "))}
  ${card(640, 194, "Warnings", String(result.counts.warnings), warnings.slice(0, 2).map((finding) => finding.code).join(" / "))}
  ${card(912, 194, "Tasks", String(tasks.length), tasks[0]?.title ?? "No reviewer tasks")}
  <rect x="96" y="396" width="1088" height="176" rx="14" fill="#18232d"/>
  <text x="128" y="446" font-family="Inter, Arial, sans-serif" font-size="22" font-weight="700" fill="#ffffff">Export packet</text>
  <text x="128" y="486" font-family="Menlo, Consolas, monospace" font-size="17" fill="#c9f2d0">${escapeXml(result.exportPacket.auditDigest)}</text>
  <text x="128" y="528" font-family="Inter, Arial, sans-serif" font-size="17" fill="#dce4e8">Ready: ${result.ready ? "yes" : "no"} | Pinned sources: ${result.sidebarCoverage.pinnedSources} | Resolved threads: ${result.sidebarCoverage.resolvedThreads}/${result.sidebarCoverage.totalThreads}</text>
  <text x="96" y="628" font-family="Inter, Arial, sans-serif" font-size="16" fill="#5d5750">Generated by npm run demo for SCIBASE issue #12 review.</text>
</svg>
`;
}

function card(x, y, label, value, detail) {
  return `<rect x="${x}" y="${y}" width="232" height="142" rx="12" fill="#f1eee7" stroke="#d8d1c4"/>
  <text x="${x + 24}" y="${y + 42}" font-family="Inter, Arial, sans-serif" font-size="16" font-weight="700" fill="#5d5750">${escapeXml(label)}</text>
  <text x="${x + 24}" y="${y + 82}" font-family="Inter, Arial, sans-serif" font-size="32" font-weight="700" fill="#24211d">${escapeXml(value)}</text>
  <text x="${x + 24}" y="${y + 116}" font-family="Inter, Arial, sans-serif" font-size="13" fill="#70685f">${escapeXml(detail).slice(0, 46)}</text>`;
}

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
