#import <AppKit/AppKit.h>
#import <AVFoundation/AVFoundation.h>

static const NSInteger FrameWidth = 1280;
static const NSInteger FrameHeight = 720;
static const NSInteger FramesPerSecond = 30;
static const NSInteger TotalFrames = 150;

static void FillRounded(NSRect rect, CGFloat radius, NSColor *color) {
  NSBezierPath *path = [NSBezierPath bezierPathWithRoundedRect:rect xRadius:radius yRadius:radius];
  [color setFill];
  [path fill];
}

static void DrawText(NSString *text, CGFloat x, CGFloat y, CGFloat width, CGFloat height, CGFloat size, NSColor *color, BOOL bold) {
  NSFont *font = bold ? [NSFont systemFontOfSize:size weight:NSFontWeightSemibold] : [NSFont systemFontOfSize:size weight:NSFontWeightRegular];
  NSDictionary *attributes = @{
    NSFontAttributeName: font,
    NSForegroundColorAttributeName: color
  };
  [text drawInRect:NSMakeRect(x, y, width, height) withAttributes:attributes];
}

static NSColor *Color(CGFloat red, CGFloat green, CGFloat blue) {
  return [NSColor colorWithCalibratedRed:red / 255.0 green:green / 255.0 blue:blue / 255.0 alpha:1.0];
}

static void DrawFrame(CGContextRef context, NSInteger frameIndex) {
  NSGraphicsContext *graphicsContext = [NSGraphicsContext graphicsContextWithCGContext:context flipped:NO];
  [NSGraphicsContext saveGraphicsState];
  [NSGraphicsContext setCurrentContext:graphicsContext];

  [[NSColor colorWithCalibratedRed:247.0 / 255.0 green:244.0 / 255.0 blue:238.0 / 255.0 alpha:1.0] setFill];
  NSRectFill(NSMakeRect(0, 0, FrameWidth, FrameHeight));

  FillRounded(NSMakeRect(54, 48, 1172, 624), 18, [NSColor whiteColor]);
  DrawText(@"Collaborative Discussion Sidebar Audit", 92, 604, 720, 44, 34, Color(36, 33, 29), YES);
  DrawText(@"SCIBASE issue #12 slice: section chat, pinned evidence, decisions, and export packet.", 92, 570, 860, 28, 18, Color(93, 87, 80), NO);

  CGFloat progress = (CGFloat)frameIndex / (CGFloat)(TotalFrames - 1);
  FillRounded(NSMakeRect(92, 534, 1080, 12), 6, Color(229, 223, 214));
  FillRounded(NSMakeRect(92, 534, 1080 * progress, 12), 6, Color(30, 129, 176));

  NSArray<NSString *> *labels = @[@"Coverage", @"Blockers", @"Warnings", @"Tasks"];
  NSArray<NSString *> *values = @[@"3/3", @"5", @"3", @"1"];
  NSArray<NSString *> *details = @[@"sidebar scopes", @"must resolve", @"review notes", @"owner handoff"];
  for (NSInteger index = 0; index < 4; index++) {
    CGFloat x = 92 + index * 270;
    FillRounded(NSMakeRect(x, 374, 238, 130), 14, Color(241, 238, 231));
    DrawText(labels[index], x + 22, 460, 180, 24, 16, Color(93, 87, 80), YES);
    DrawText(values[index], x + 22, 416, 160, 42, 32, Color(36, 33, 29), YES);
    DrawText(details[index], x + 22, 394, 180, 22, 14, Color(112, 104, 95), NO);
  }

  FillRounded(NSMakeRect(92, 146, 1088, 174), 16, Color(24, 35, 45));
  DrawText(@"Export packet", 126, 272, 240, 32, 22, [NSColor whiteColor], YES);
  DrawText(@"scibase-paper-alpha:5:3:1:deterministic", 126, 226, 780, 30, 18, Color(201, 242, 208), NO);
  DrawText(@"Ready: no | Pinned sources: 3 | Resolved threads: 2/4 | Deterministic handoff for version history", 126, 188, 920, 28, 17, Color(220, 228, 232), NO);

  CGFloat pulse = 0.45 + 0.35 * sin(progress * M_PI * 4.0);
  NSColor *pulseColor = [NSColor colorWithCalibratedRed:30.0 / 255.0 green:129.0 / 255.0 blue:176.0 / 255.0 alpha:pulse];
  FillRounded(NSMakeRect(1008, 214, 126, 44), 22, pulseColor);
  DrawText(@"demo.mp4", 1033, 226, 90, 22, 15, [NSColor whiteColor], YES);

  DrawText(@"Generated by npm run demo:video", 92, 92, 360, 24, 15, Color(93, 87, 80), NO);

  [NSGraphicsContext restoreGraphicsState];
}

static BOOL AppendFrame(AVAssetWriterInputPixelBufferAdaptor *adaptor, CMTime time, NSInteger frameIndex) {
  CVPixelBufferRef pixelBuffer = NULL;
  CVReturn result = CVPixelBufferPoolCreatePixelBuffer(NULL, adaptor.pixelBufferPool, &pixelBuffer);
  if (result != kCVReturnSuccess || pixelBuffer == NULL) {
    return NO;
  }

  CVPixelBufferLockBaseAddress(pixelBuffer, 0);
  void *baseAddress = CVPixelBufferGetBaseAddress(pixelBuffer);
  size_t bytesPerRow = CVPixelBufferGetBytesPerRow(pixelBuffer);
  CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
  CGContextRef context = CGBitmapContextCreate(baseAddress, FrameWidth, FrameHeight, 8, bytesPerRow, colorSpace, kCGImageAlphaPremultipliedFirst | kCGBitmapByteOrder32Host);

  DrawFrame(context, frameIndex);

  CGContextRelease(context);
  CGColorSpaceRelease(colorSpace);
  CVPixelBufferUnlockBaseAddress(pixelBuffer, 0);

  BOOL appended = [adaptor appendPixelBuffer:pixelBuffer withPresentationTime:time];
  CVPixelBufferRelease(pixelBuffer);
  return appended;
}

int main(int argc, const char *argv[]) {
  @autoreleasepool {
    if (argc < 2) {
      fprintf(stderr, "usage: render-demo-video output.mp4\n");
      return 1;
    }

    NSString *outputPath = [NSString stringWithUTF8String:argv[1]];
    NSURL *outputURL = [NSURL fileURLWithPath:outputPath];
    [[NSFileManager defaultManager] removeItemAtURL:outputURL error:nil];

    NSError *error = nil;
    AVAssetWriter *writer = [[AVAssetWriter alloc] initWithURL:outputURL fileType:AVFileTypeMPEG4 error:&error];
    if (!writer) {
      fprintf(stderr, "failed to create writer: %s\n", error.localizedDescription.UTF8String);
      return 1;
    }

    NSDictionary *settings = @{
      AVVideoCodecKey: AVVideoCodecTypeH264,
      AVVideoWidthKey: @(FrameWidth),
      AVVideoHeightKey: @(FrameHeight),
      AVVideoCompressionPropertiesKey: @{
        AVVideoAverageBitRateKey: @(1800000)
      }
    };
    AVAssetWriterInput *input = [AVAssetWriterInput assetWriterInputWithMediaType:AVMediaTypeVideo outputSettings:settings];
    input.expectsMediaDataInRealTime = NO;

    NSDictionary *attributes = @{
      (NSString *)kCVPixelBufferPixelFormatTypeKey: @(kCVPixelFormatType_32BGRA),
      (NSString *)kCVPixelBufferWidthKey: @(FrameWidth),
      (NSString *)kCVPixelBufferHeightKey: @(FrameHeight)
    };
    AVAssetWriterInputPixelBufferAdaptor *adaptor = [AVAssetWriterInputPixelBufferAdaptor assetWriterInputPixelBufferAdaptorWithAssetWriterInput:input sourcePixelBufferAttributes:attributes];

    if (![writer canAddInput:input]) {
      fprintf(stderr, "writer cannot add video input\n");
      return 1;
    }
    [writer addInput:input];

    [writer startWriting];
    [writer startSessionAtSourceTime:kCMTimeZero];

    for (NSInteger frame = 0; frame < TotalFrames; frame++) {
      while (!input.readyForMoreMediaData) {
        [NSThread sleepForTimeInterval:0.01];
      }
      CMTime time = CMTimeMake(frame, FramesPerSecond);
      if (!AppendFrame(adaptor, time, frame)) {
        fprintf(stderr, "failed to append frame %ld\n", (long)frame);
        return 1;
      }
    }

    [input markAsFinished];
    dispatch_semaphore_t semaphore = dispatch_semaphore_create(0);
    [writer finishWritingWithCompletionHandler:^{
      dispatch_semaphore_signal(semaphore);
    }];
    dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);

    if (writer.status != AVAssetWriterStatusCompleted) {
      fprintf(stderr, "failed to write video: %s\n", writer.error.localizedDescription.UTF8String);
      return 1;
    }

    printf("wrote %s\n", outputPath.UTF8String);
  }
  return 0;
}
